# NUMPY

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [3]:
array = np.array(lista)

In [4]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy arrays - arange, zeros, ones, linspace, eye

In [9]:
import numpy as np

In [10]:
array = np.arange(5) #Genera un array con una secuencia del 0 al 4 (5-1)

In [11]:
array

array([0, 1, 2, 3, 4])

In [12]:
np.arange(2,8) #Genera un array del 2 hasta el 7 (8-1)

array([2, 3, 4, 5, 6, 7])

In [13]:
np.arange(2,20,4) #Genera un array del 2 hasta el 19(20-1) de 4 en 4

array([ 2,  6, 10, 14, 18])

In [14]:
np.zeros(5) #Genera un array de largo 5, con puros 0 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros([5,10]) #Array de dos dimensiones, filas x columnas

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
array = np.ones(5) #Genera un array de largo 5, con puros 1

In [17]:
np.ones([7,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(6,8,50) #Genera un array que parte del 6, termina en 8 y tiene 50 espacios


array([6.        , 6.04081633, 6.08163265, 6.12244898, 6.16326531,
       6.20408163, 6.24489796, 6.28571429, 6.32653061, 6.36734694,
       6.40816327, 6.44897959, 6.48979592, 6.53061224, 6.57142857,
       6.6122449 , 6.65306122, 6.69387755, 6.73469388, 6.7755102 ,
       6.81632653, 6.85714286, 6.89795918, 6.93877551, 6.97959184,
       7.02040816, 7.06122449, 7.10204082, 7.14285714, 7.18367347,
       7.2244898 , 7.26530612, 7.30612245, 7.34693878, 7.3877551 ,
       7.42857143, 7.46938776, 7.51020408, 7.55102041, 7.59183673,
       7.63265306, 7.67346939, 7.71428571, 7.75510204, 7.79591837,
       7.83673469, 7.87755102, 7.91836735, 7.95918367, 8.        ])

In [19]:
np.linspace(3,20,18)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
       16., 17., 18., 19., 20.])

In [20]:
np.eye(6) #Genera una matriz cuadrada 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Números aleatorios - rand y randn


In [21]:
import numpy as np

In [22]:
np.random.rand(5) #Genera un array de 5 espacios de n° aleatorios 

array([0.5575451 , 0.62263253, 0.73264638, 0.64281674, 0.19823757])

In [23]:
np.random.rand(2,3) #Genera una matriz(2x3) de n° aleatorios 

array([[0.70591753, 0.02094964, 0.38258806],
       [0.50042858, 0.30243152, 0.53755715]])

In [24]:
np.random.randn(4) 

array([ 0.31030661, -0.35315075, -0.44757115, -0.57739314])

In [25]:
np.random.randn(6,9)

array([[-0.22014762, -0.23503237,  0.04377979, -0.76781607, -1.44639312,
         1.80179874, -0.32273613, -1.17978547, -1.54029996],
       [ 0.80157292,  1.06527673,  0.07743059, -2.23935832,  0.55667573,
         0.29192787, -1.57857976, -1.20676667, -0.40915627],
       [-0.67636882,  0.73342866,  1.29740868,  0.59461703, -0.03642108,
        -1.26380113,  0.18863562,  0.45624331,  0.72126521],
       [ 2.41611337,  1.24596132, -0.32917775, -0.67342392, -1.27966493,
        -0.95476202, -0.52112458, -0.03865797, -0.84678687],
       [ 3.35274863,  0.32766596, -0.11259238, -0.06957935,  0.07840421,
        -0.24512468, -0.50578806,  0.88867119, -0.88646817],
       [ 0.10265867,  0.97980164, -2.11374809, -0.49605189,  1.11945093,
         2.22413277,  0.45371969, -1.64383213, -0.0841194 ]])

# numpy arrays - números aleatorios enteros y randint

In [26]:
import numpy as np

In [27]:
np.random.randint(1,20) #Genera 1 número random entre el 1 y el 19 (20-1)

10

In [28]:
np.random.randint(1,20,5) #Genera un array de 5 espacios con números random entre el 1 y el 19 (20-1)

array([13, 15, 11,  4,  8])

# Numpy arrays - reshape


In [29]:
import numpy as np

In [30]:
array = np.random.randint(1,100,21) #Genera una array de 21 espacios con numeros random del 1 al 99 (100-1)

In [31]:
array

array([14, 27, 96, 69, 82, 82, 60, 59, 14, 46, 17, 53, 23, 15, 32, 28, 24,
       80,  5, 19, 71])

In [32]:
matriz = array.reshape(3,7) #A partir de un array, genera una matriz (3x7)

In [33]:
matriz

array([[14, 27, 96, 69, 82, 82, 60],
       [59, 14, 46, 17, 53, 23, 15],
       [32, 28, 24, 80,  5, 19, 71]])


# Numpy arrays - max y min

In [34]:
import numpy as np

In [35]:
array = np.random.randint(1,100,50) #Genera una array de 50 espacios con numeros random del 1 al 99 (100-1)

In [36]:
array

array([61, 21, 46, 93, 66, 38, 68, 30,  2, 43, 76, 93, 44, 90, 79, 50, 79,
       91, 71, 76, 41, 67, 82, 90, 15, 44, 88, 44, 12, 22, 54, 96, 58, 88,
       60, 71, 21, 93, 44, 33, 35, 89, 31,  6, 53, 22, 45, 47, 84, 55])

In [37]:
valor_maximo = array.max()

In [38]:
valor_maximo

96

In [39]:
posicion_valor_maximo = array.argmax() #Dice en que posicion del array esta el maximo 

In [40]:
posicion_valor_maximo

31

In [41]:
valor_minimo = array.min()

In [42]:
valor_minimo

2

In [43]:
posicion_valor_minimo = array.argmin() #Dice en que posicion del array esta el mínimo 

In [44]:
posicion_valor_minimo

8

# Numpy - Indexación en Arrays

In [45]:
import numpy as np

In [46]:
array = np.arange(0,10)

In [47]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
array[0] #valor en la posición 0

0

In [49]:
array[4] #valor en la posición 4

4

In [50]:
array[-1] #valor en la ultima posición 

9

In [51]:
array[2:4] #valores de la posición 2, hasta la 3 (4-1)

array([2, 3])

In [52]:
array[2:8] #valores de la posición 2, hasta la 7 (8-1)

array([2, 3, 4, 5, 6, 7])

In [53]:
array[:] 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array[2:] #valores de la posición 5, hasta la ultima

array([2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
array[:5] #valores de la primera posición, hasta la posición 4 (5-1)

array([0, 1, 2, 3, 4])

In [56]:
array2 = array.copy()

In [57]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy - indexación en arrays de 2 o más dimensiones

In [58]:
import numpy as np

In [59]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
array[0]

array([1, 2, 3])

In [62]:
array[2]

array([7, 8, 9])

In [63]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
array2 = array[:2]

In [65]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
array[0][0]

1

In [68]:
array[0,0]

1

In [69]:
array[1,1]

5

In [70]:
array[:,0]

array([1, 4, 7])

In [71]:
array[:,2]

array([3, 6, 9])

In [72]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Numpy - Sleccionar elementos de un array según una condición

In [73]:
import numpy as np

In [74]:
array = np.arange(0,10)

In [75]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
condicion = array > 5

In [77]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [78]:
array[condicion]

array([6, 7, 8, 9])

In [79]:
array6 = array[condicion]

In [80]:
array6

array([6, 7, 8, 9])

In [81]:
array[array > 5]

array([6, 7, 8, 9])

In [82]:
array[array % 2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [83]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

In [84]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy - Operaciones sobre los arrays

In [85]:
import numpy as np

In [86]:
array = np.arange(0,10)

In [87]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [91]:
array + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [92]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [93]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [94]:
array * -1

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [95]:
array2 = np.arange(5,15)

In [96]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [99]:
array2 + array

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [100]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [101]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [102]:
np.max(array)

9

In [103]:
np.min(array)

0