# Ejemplo de Regresión con TensorFlow

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
casas = pd.read_csv('precios_casas.csv')

In [3]:
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [4]:
casas_x = casas.drop('median_house_value', axis=1)
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [5]:
casas_y = casas['median_house_value']
casas_y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
5         74000.0
6         82400.0
7         48500.0
8         58400.0
9         48100.0
10        86500.0
11        62000.0
12        48600.0
13        70400.0
14        45000.0
15        69100.0
16        94900.0
17        25000.0
18        44000.0
19        27500.0
20        44400.0
21        59200.0
22        50000.0
23        71300.0
24        53500.0
25       100000.0
26        71100.0
27        80900.0
28        68600.0
29        74300.0
           ...   
16970     75500.0
16971     62500.0
16972     70500.0
16973     68300.0
16974     81300.0
16975     82800.0
16976    116100.0
16977     86400.0
16978     70500.0
16979     70200.0
16980     67000.0
16981     72200.0
16982    107000.0
16983     74600.0
16984     70000.0
16985     69000.0
16986     90100.0
16987     68400.0
16988     66900.0
16989     58100.0
16990     78300.0
16991     73200.0
16992     50800.0
16993    106700.0
16994     

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(casas_x, casas_y, test_size = 0.3)

In [8]:
X_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5179     -118.13     33.91                35.0        561.0           104.0   
4836     -118.09     33.84                23.0       4412.0           910.0   
13559    -121.97     37.53                35.0       2277.0           420.0   
16222    -122.48     37.76                50.0       2236.0           484.0   
6391     -118.26     34.01                37.0       2451.0           668.0   

       population  households  median_income  
5179        261.0       105.0         4.9375  
4836       2380.0       825.0         4.5400  
13559      1353.0       413.0         4.7500  
16222      1171.0       467.0         4.0977  
6391       2824.0       598.0         1.9074

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
normalizador = MinMaxScaler()

In [11]:
normalizador.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [12]:
X_train = pd.DataFrame(data= normalizador.transform(X_train), columns=X_train.columns, index=X_train.index)

In [13]:
X_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5179    0.619522  0.144681            0.666667     0.017134        0.015831   
4836    0.623506  0.137234            0.431373     0.135172        0.140928   
13559   0.237052  0.529787            0.666667     0.069732        0.064877   
16222   0.186255  0.554255            0.960784     0.068475        0.074810   
6391    0.606574  0.155319            0.705882     0.075065        0.103368   
13653   0.235060  0.575532            0.313725     0.084414        0.065342   
10961   0.343625  0.787234            0.372549     0.041287        0.036629   
8647    0.578685  0.173404            0.470588     0.059341        0.070619   
5913    0.611554  0.222340            0.294118     0.078805        0.065963   
1088    0.721116  0.020213            0.470588     0.020904        0.029179   
5405    0.617530  0.137234            0.549020     0.074973        0.054633   
1209    0.719124  0.018085            0.156863     0.074605        0.111439   
11033   0.337649  0.544681            0.333333     0.044138        0.035232   
12136   0.289841  0.632979            0.509804     0.077395        0.067826   
10460   0.397410  0.380851            0.549020     0.059341        0.067050   
3226    0.646414  0.179787            1.000000     0.024552        0.041130   
1511    0.711155  0.162766            0.078431     0.176153        0.214652   
14342   0.224104  0.514894            0.588235     0.034176        0.046873   
7030    0.601594  0.128723            0.490196     0.137441        0.109731   
8929    0.546813  0.175532            0.607843     0.073471        0.059289   
10361   0.419323  0.217021            0.156863     0.077670        0.077138   
9911    0.460159  0.443617            0.274510     0.068782        0.070464   
1261    0.718127  0.021277            0.509804     0.047479        0.071706   
9857    0.462151  0.445745            0.333333     0.248184        0.258886   
16230   0.186255  0.552128            1.000000     0.075126        0.078535   
9493    0.503984  0.425532            0.392157     0.075556        0.080397   
7819    0.593625  0.156383            0.725490     0.077211        0.100109   
12578   0.266932  0.438298            0.450980     0.094069        0.084122   
1757    0.707171  0.026596            0.588235     0.066820        0.097470   
13770   0.233068  0.576596            0.607843     0.092261        0.081484   
...          ...       ...                 ...          ...             ...   
16216   0.186255  0.556383            0.921569     0.086835        0.112680   
14584   0.218127  0.551064            1.000000     0.069211        0.064256   
2065    0.699203  0.151064            0.137255     0.004598        0.002639   
11704   0.303785  0.581915            0.058824     0.046375        0.059289   
13336   0.242032  0.426596            0.745098     0.065655        0.083191   
2251    0.691235  0.151064            0.647059     0.070927        0.056340   
1287    0.717131  0.157447            0.490196     0.162544        0.108490   
15579   0.200199  0.534043            1.000000     0.080705        0.063014   
7814    0.593625  0.158511            0.784314     0.003034        0.003259   
518     0.732072  0.248936            0.549020     0.080766        0.079156   
11938   0.296813  0.644681            0.745098     0.025165        0.022350   
1307    0.717131  0.021277            0.509804     0.096981        0.134254   
13722   0.234064  0.530851            0.549020     0.126621        0.115164   
720     0.727092  0.018085            0.666667     0.054406        0.056961   
2987    0.654382  0.120213            0.254902     0.053579        0.051839   
12529   0.269920  0.697872            0.333333     0.098391        0.083812   
10878   0.350598  0.526596            0.568627     0.041011        0.037560   
1129    0.720120  0.037234            0.235294     0.053364        0.056030   
7498    0.596614  0.159574            0.921569     0.0561

In [14]:
X_test = pd.DataFrame(data= normalizador.transform(X_test), columns=X_test.columns, index=X_test.index)

In [15]:
X_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7766   0.594622  0.134043            0.372549     0.060475        0.047183   
4364   0.630478  0.148936            0.725490     0.065502        0.065808   
5134   0.619522  0.173404            1.000000     0.094774        0.080242   
5097   0.620518  0.141489            0.686275     0.033134        0.033525   
7056   0.600598  0.169149            0.431373     0.140138        0.220549   

      population  households  median_income  
7766    0.019619    0.047697       0.555110  
4364    0.031811    0.067434       0.261500  
5134    0.036604    0.079934       0.408436  
5097    0.015527    0.034211       0.177901  
7056    0.045433    0.163322       0.248038

In [16]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [17]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')

In [18]:
columnas = [longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income]

In [19]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=1000, shuffle=True)

In [20]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Cata\\AppData\\Local\\Temp\\tmpjet8is0v', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000141D5AA2550>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [21]:
modelo.train(input_fn = funcion_entrada, steps=8000) 

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use `tf.cast` instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Cata\AppData\Local\Temp\tmpjet8is0v\model.ckpt.
INFO:tensorflow:loss = 457032070000.0, step = 1
INFO:tensorflow:global_step/sec: 203.79
INFO:tensorflow:loss = 617723400000.0, step = 101 (0.491 sec)
INFO:tensorflow:global_step/sec: 464.145
INFO:tensorflow:loss = 456007420000.0, step = 201 (0.212 sec)
INFO:tensorflow:global_step/sec: 470.033
INFO:tensorflow:loss = 352229600000.0, step = 301 (0.214 sec)
INFO:tensorflow:global_step/sec: 490.268
INFO:tensorflow:loss = 106991640000.0, step = 401 (0.202 sec)
INFO:tensorflow:global_step/sec: 484.386
INFO:tensorflow:l

INFO:tensorflow:global_step/sec: 328.745
INFO:tensorflow:loss = 104736326000.0, step = 6501 (0.306 sec)
INFO:tensorflow:global_step/sec: 282.643
INFO:tensorflow:loss = 88852890000.0, step = 6601 (0.356 sec)
INFO:tensorflow:global_step/sec: 277.753
INFO:tensorflow:loss = 29959377000.0, step = 6701 (0.357 sec)
INFO:tensorflow:global_step/sec: 326.964
INFO:tensorflow:loss = 140889750000.0, step = 6801 (0.307 sec)
INFO:tensorflow:global_step/sec: 189.541
INFO:tensorflow:loss = 174631830000.0, step = 6901 (0.528 sec)
INFO:tensorflow:global_step/sec: 253.843
INFO:tensorflow:loss = 137785340000.0, step = 7001 (0.393 sec)
INFO:tensorflow:global_step/sec: 234.269
INFO:tensorflow:loss = 47757330000.0, step = 7101 (0.429 sec)
INFO:tensorflow:global_step/sec: 248.097
INFO:tensorflow:loss = 51555918000.0, step = 7201 (0.401 sec)
INFO:tensorflow:global_step/sec: 262.37
INFO:tensorflow:loss = 67118227000.0, step = 7301 (0.381 sec)
INFO:tensorflow:global_step/sec: 274.705
INFO:tensorflow:loss = 416819

In [22]:
funcion_prediccion = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=10, num_epochs=1, shuffle=False)

In [23]:
generador_predicciones = modelo.predict(input_fn = funcion_prediccion)

In [24]:
predicciones = list(generador_predicciones)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\Cata\AppData\Local\Temp\tmpjet8is0v\model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [25]:
predicciones

[{'predictions': array([258291.64], dtype=float32)},
 {'predictions': array([230837.17], dtype=float32)},
 {'predictions': array([285300.94], dtype=float32)},
 {'predictions': array([203279.55], dtype=float32)},
 {'predictions': array([226014.53], dtype=float32)},
 {'predictions': array([154002.11], dtype=float32)},
 {'predictions': array([221006.7], dtype=float32)},
 {'predictions': array([290041.28], dtype=float32)},
 {'predictions': array([221602.52], dtype=float32)},
 {'predictions': array([214383.03], dtype=float32)},
 {'predictions': array([222536.98], dtype=float32)},
 {'predictions': array([206161.3], dtype=float32)},
 {'predictions': array([233637.36], dtype=float32)},
 {'predictions': array([195279.61], dtype=float32)},
 {'predictions': array([191935.62], dtype=float32)},
 {'predictions': array([195264.08], dtype=float32)},
 {'predictions': array([227336.48], dtype=float32)},
 {'predictions': array([269795.2], dtype=float32)},
 {'predictions': array([224471.27], dtype=float32

In [26]:
predicciones_finales = []
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])


In [27]:
predicciones_finales

[array([258291.64], dtype=float32),
 array([230837.17], dtype=float32),
 array([285300.94], dtype=float32),
 array([203279.55], dtype=float32),
 array([226014.53], dtype=float32),
 array([154002.11], dtype=float32),
 array([221006.7], dtype=float32),
 array([290041.28], dtype=float32),
 array([221602.52], dtype=float32),
 array([214383.03], dtype=float32),
 array([222536.98], dtype=float32),
 array([206161.3], dtype=float32),
 array([233637.36], dtype=float32),
 array([195279.61], dtype=float32),
 array([191935.62], dtype=float32),
 array([195264.08], dtype=float32),
 array([227336.48], dtype=float32),
 array([269795.2], dtype=float32),
 array([224471.27], dtype=float32),
 array([181052.94], dtype=float32),
 array([199143.11], dtype=float32),
 array([215778.45], dtype=float32),
 array([271416.94], dtype=float32),
 array([173641.86], dtype=float32),
 array([203106.1], dtype=float32),
 array([213064.12], dtype=float32),
 array([257415.3], dtype=float32),
 array([193231.88], dtype=float32

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
mean_squared_error(y_test, predicciones_finales)**0.5

99327.4860454822