# Red Neuronal con TensorFlow

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
aleatorio_a = np.random.uniform(0,50,(4,4))

In [4]:
aleatorio_a

array([[10.09528529,  6.40770451, 13.03598932, 43.63298249],
       [35.95123874, 41.82091986, 12.84048619, 48.17905133],
       [ 6.94212875, 24.61940668,  4.09761103, 32.45861841],
       [ 8.64771154, 37.38889915,  5.16061006, 13.55966539]])

In [6]:
aleatorio_b = np.random.uniform(0,50,(4,1))
aleatorio_b

array([[44.9931665 ],
       [ 6.00064901],
       [36.33193729],
       [39.8944921 ]])

In [7]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [8]:
suma = a + b
multiplicacion = a * b

In [10]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma, feed_dict={a:10, b:20})
    print(resultado_suma)

30.0


In [11]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma, feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_suma)

[[55.088455 51.40087  58.02916  88.62615 ]
 [41.95189  47.821568 18.841135 54.1797  ]
 [43.274063 60.95134  40.429546 68.79056 ]
 [48.542206 77.283394 45.055103 53.45416 ]]


In [12]:
with tf.Session() as sesion:
    resultado_multiplicacion = sesion.run(multiplicacion, feed_dict={a:10, b:20})
    print(resultado_multiplicacion)

200.0


In [13]:
with tf.Session() as sesion:
    resultado_multiplicacion = sesion.run(multiplicacion, feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_multiplicacion)

[[ 454.21887   288.30292   586.53046  1963.1862  ]
 [ 215.73077   250.95265    77.051254  289.10556 ]
 [ 252.22098   894.47064   148.87415  1179.2844  ]
 [ 344.99606  1491.6112    205.87993   540.956   ]]


# Ejemplo de red neuronal

In [14]:
caracteristicas = 10

In [15]:
neuronas = 4

In [16]:
x = tf.placeholder(tf.float32, (None, caracteristicas))

In [17]:
W = tf.Variable(tf.random.normal([caracteristicas, neuronas]))

In [18]:
b = tf.Variable(tf.ones([neuronas]))

In [19]:
multiplicacion = tf.matmul(x,W)

In [20]:
z = tf.add(multiplicacion,b)

In [21]:
activacion = tf.sigmoid(z)

In [22]:
inicializacion = tf.global_variables_initializer()

In [24]:
valores_x = np.random.random([1,caracteristicas])

In [25]:
valores_x

array([[0.43371136, 0.98799275, 0.48141258, 0.38844469, 0.82449802,
        0.75483207, 0.52894444, 0.00218038, 0.77337516, 0.5038998 ]])

In [26]:
with tf.Session() as sesion:
    sesion.run(inicializacion)
    resultado = sesion.run(activacion, feed_dict={x:valores_x})

In [27]:
print(resultado)

[[0.94610566 0.2079291  0.05883247 0.81113786]]
